FROM python:3.9.18-slim-bullseye

# Set the working directory in the container
WORKDIR /gpxvis

# Copy the dependencies file to the working directory
COPY src/ /gpxvis/

# Install any dependencies
RUN pip3 install -r requirements.txt
RUN rm requirements.txt

# Listen on port 5000
EXPOSE 5000

# Run flask
ENTRYPOINT ["python3", "-m", "flask", "run", "--host=0.0.0.0"]