name: gpxvis.com

on:
  push:
    branches: ['main']

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Upload updated flask code
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "*"
          target: ${{ secrets.DEPLOY_PATH }}
          tar_tmp_path: ${{ secrets.TEMP_PATH }}
          rm: true
          timeout: 60s

      - name: Install Flask dependencies and restart Flask
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            pip3 install -r ${{ secrets.DEPLOY_PATH }}/requirements.txt
            sudo systemctl restart ${{ secrets.DAEMON_NAME }}
